name: Code Check

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        shell: bash
    steps:
      - name: Print GitHub context
        run: |
          echo "Current GitHub context:"
          echo "${{ toJson(github) }}"
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read random.txt
        id: read_random
        run: |
          if [ -f random.txt ]; then
            echo "random.txt exists. Contents:"
            cat random.txt
          else
            echo "random.txt does not exist."
          fi
