name: Codegen

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-gen:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print GitHub context
        run: |
          echo "Current GitHub context:"
          echo "${{ toJson(github) }}"

      - name: Create a branch with datetime
        run: |
          random_string=$(openssl rand -hex 3)
          branch_name="branch-$(date +'%Y%m%d%H%M%S')-$random_string"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "RANDOM_STRING=$random_string" >> $GITHUB_ENV

      - name: Add a random string to ./random.txt
        run: |
          echo "$RANDOM_STRING" >> random.txt
          echo "Added random string: $RANDOM_STRING to random.txt"

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Add random string to random.txt"
          body: "This PR adds a random string to random.txt"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          draft: false
