name: Code Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read random.txt
        id: read_random
        run: |
          if [ -f random.txt ]; then
            echo "random.txt exists. Contents:"
            cat random.txt
          else
            echo "random.txt does not exist."
          fi

      - name: Create a commit status
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Create a new commit status for the current commit
              const status = await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: 'success',
                context: 'code-check',
                description: 'The code check has passed successfully.',
                target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              });
              console.log('Commit status created:', status.data);
            } catch (error) {
              console.error('Error creating commit status:', error);
              throw error;
            }
